file_format: "1"
id: sofle
name: The sofle 
type: shield
url: https://github.com/benvallack/zmk-config-sofle
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - sofle_left
  - sofle_right
  - sofle_dongle
